[package]
name = "binius_m3"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
anyhow.workspace = true
binius_core = { path = "../core" }
binius_field = { path = "../field", default-features = false }
binius_math = { path = "../math" }
binius_maybe_rayon = { path = "../maybe_rayon" }
binius_utils = { path = "../utils", default-features = false }
bumpalo.workspace = true
bytemuck.workspace = true
getset.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_matches.workspace = true
binius_hal = { path = "../hal" }
binius_hash = { path = "../hash", default-features = false }
groestl_crypto.workspace = true
rand.workspace = true

[features]
default = ["binius_utils/rayon"]
