[package]
name = "binius_compute"
version.workspace = true
edition.workspace = true
authors.workspace = true

[lints]
workspace = true

[dependencies]
binius_field = { path = "../field", default-features = false }
bytemuck.workspace = true
thiserror.workspace = true

[dev-dependencies]
assert_matches.workspace = true
binius_math = { path = "../math", default-features = false }
rand.workspace = true
