[package]
name = "binius_backend_provider"
version.workspace = true
edition.workspace = true
authors.workspace = true

[dependencies]
binius_hal = { path = "../hal" }
linerate-binius-backend = { workspace = true, optional = true }

[features]
linerate-backend = ["linerate-binius-backend"]