[build]
rustdocflags = ["-Dwarnings", "--html-in-header", "doc/katex-header.html"]

[target.wasm32-unknown-unknown]
rustflags = ['--cfg', 'getrandom_backend="wasm_js"']

[alias]
fast_test = "test --tests"
